CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50),
  password VARCHAR(255),
  instrument VARCHAR(255)
);

CREATE TABLE songs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  artist VARCHAR(255),
  content LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
);